/****** Object:  View [idc_bmi].[dbs_ECA_CMNCMN]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW [idc_bmi].[dbs_ECA_CMNCMN]
AS

SELECT


 LASTMODIFIED
 ,IDCMLSNUMBER
 ,IDCLISTPRICE
 ,IDCLISTDATE
 ,IDCPROPERTYTYPE= idc_bmi.fn_Get_ECA_IDCPROPERTYTYPE(IDCPROPERTYTYPE,PROPERTYTYPE)
 ,PROPERTYTYPE
 ,YEARBUILT
 ,IDCADDRESS
 ,CITY
 ,STATE
 ,AREA
 ,ZIPCODE
 ,COUNTY
 ,BEDS = isnull(BEDS,0)
 ,BATHS
 ,BATHSFULL
 ,BATHSHALF
 ,ACRES=LOTSIZE
 ,SQFT
 ,IDCISBROKER
 ,IDCLISTAGENTNAME
 ,IDCCOLISTAGENTNAME
 ,MLSNUMBER
 ,IDCLATITUDE = CASE WHEN (IDCLATITUDE between -90 and 90) THEN IDCLATITUDE  ELSE NULL END
 ,MODIFIEDDATE
 ,IDCLONGITUDE =CASE WHEN (IDCLONGITUDE between -180 and 180) THEN IDCLONGITUDE  ELSE NULL END
 ,IDCCOLISTAGENTID
 ,IDCCOLISTOFFICEID
 ,IDCCOLISTOFFICENAME
 ,IDCDISPLAYADDRESS
  ,IDCDISPLAYONWEBSITE = CASE WHEN (IDCDISPLAYONWEBSITE = 'NO')  THEN  0 ELSE CASE WHEN  STATE  IN ('MI','IN') THEN  1 ELSE 0  END END
 ,IDCFULLADDRESS
 ,IDCLISTAGENTID
 ,IDCLISTOFFICEID
 ,IDCLISTOFFICENAME
 ,IDCREMARKS
 ,MLSDOM
 ,MLSPHOTOCOUNT
 ,PHOTOMODIFIEDDATE
 ,PROPERTYPK
 ,PROPERTYRT
 ,VIRTUALTOUR
 ,CALCLISTPRICEPERSQFT
 ,CALCMCEDATE
 ,CALCOPENHOUSECHANGEDATE
 ,CALCPREVIOUSPRICE
 ,CALCPREVIOUSSTATUS
 ,CALCPRICEBYSTATUS
 ,CALCPRICECHANGE
 ,CALCPRICECHANGEDATE
 ,CALCPRICEPERSQFT
 ,CALCSTATUSCHANGEDATE
 ,IDCRADIUSX
 ,IDCRADIUSY
 ,IDCRADIUSZ
 ,SUBDIVISION
 ,COOLINGDESC
 ,ELEMENTARYSCHOOL
 ,EXTERIORFEATURES
 ,FIREPLACES
 ,HIGHSCHOOL
 ,INTERIORFEATURES
 ,MIDDLESCHOOL
 ,ROOFDESC
 ,SCHOOLDISTRICT
 ,STREETDIRECTIONPREFIX
 ,STREETNAME
 ,STREETNUMBER
 ,STYLE
 ,ZONING



  ,BATHSTOTAL =  isnull(BATHS,0)
 ,AGE = null
 ,GARAGESPACE
 ,NOOFSTORIES = null
 ,ISFIREPLACE  = CASE WHEN FIREPLACEYN = 'Yes' THEN  1 ELSE 0 END

 ,ISPRICEREDUCED = (CONVERT([bit],case when CONVERT([date],s.[calcpricechangedate])>=CONVERT([date],getdate()-(30)) AND CONVERT([date],s.[calcpricechangedate])<=CONVERT([date],getdate()) then case when (isnull(s.[CALCPREVIOUSPRICE],(0))-isnull(s.[IDCLISTPRICE],(0)))>(0) then (1) else (0) end else (0) end))
 ,ISPENDING = 0 
 ,ISRENTAL =  case when s.FORSALEORRENT ='For Rent' THEN 1  
                 when s.idcstatus = 'Leased' THEN 1  
              else 0  end 
 ,ISFORECLOSURE = null
 ,ISSHORTSALES = case when SUBJTOSHORTSALEAPPRVL ='Yes' then 1 else 0 end 
 ,ISNEWCONSTRUCTION = CASE WHEN NEWCONSTRUCTION IS NULL THEN 0 else 1 end
 ,ISREO = null
 ,EXCLUDELISTING = null
 ,MLSBOARD = 'ECA'
 ,RENTALPRICE = null
 --,SEARCHBY = null
 ,LOTSQFT = null
 ,HOA = null
 ,NEIGHBORHOODNAME = null
 --,PROPERTYPHOTOS = null
 ,ISVIRTUALOPENHOUSE = null
 ,CALCVIRTUALOPENHOUSECHANGEDATE = null
 ,IDCDOM = null
 --,IDCCLUSTER = null
 ,HOAFEE = null
 ,TAX = TOTALTAXAMOUNT
  ,LINKCOMPANY = null
 ,FIREPLACEDESC = null
 ,FLOORDESC = null
 ,GARAGEDESC = GARAGE
 ,HEATINGDESC = HEATING
 ,JUNIORSCHOOL = null
 ,LOTDESC = LOTDESCRIPTION
 ,LOTDIM = null
 ,NOOFUNITS = null
 ,PARKINGDESC = PARKING 
 ,PARKINGSPACE = null
 ,POOLDESC = null  
 ,SEWERDESC = SEWERSEPTIC
 --,PENDINGDATE = null
 ,STORIES = null
 ,STREETDIRECTIONSUFIX = null
 ,STREETNAMESUFIX = null
 ,UNITNO = null
 ,UTILITIES = null
 ,WATERDESC = WATER
 ,ISLUXURY=null
 ,CONSTRUCTION= null
 ,ARCHITECTURALSTYLE= STYLE
 ,BASEMENT 
 ,BASEMENTYN= CASE WHEN BASEMENTYN = 'Yes' THEN  1 ELSE 0 END
 ,GARAGEYN= CASE WHEN GARAGEYN = 'Yes' THEN  1 ELSE 0 END
 ,MANUFACTUREDYN= null
 ,DESIGN= null
 ,GARAGEDIM=GARAGEDIMENSIONS 
 ,GARAGETYPE= GARAGE
 ,FINANCING= FINANCIALTERMS
 ,OUTBUILDINGS
 ,EXTERIOR
 ,ISGARAGESIZE= null
 ,GARAGESIZE=null 
 ,BODYOFWATER
 ,WATERFEATURES 
 ,WATERFRONTDESC= null
 ,WATERFRONTFEATURES= null
 ,WATERTYPE= null

 ,IDCSTATUS=idcstatus


				 		  
,ISPOOL =POOLYN


,ISWATERFRONT = WATERFRONTYN 
					 

,GOLFYN=GOLFYN
,TOWNSHIP
,LOTSIZE
,CITYSTATE=CITY+', '+STATE
 
,CONDOYN= CASE WHEN IDCPROPERTYTYPE  IN('RESIDENTIAL CONDO') THEN
							case when PROPERTYTYPE in ('Condominium') then 1 else 0 end  else 0 end 
,BRANDEDVIRTUALTOUR=isnull(s.VIRTUALTOUR,s.VIRTUALTOUR2)
,UNBRANDEDVIRTUALTOUR=Null
,ISVIRTUALTOUR= case when  idcisbroker=1 then case when isnull(s.VIRTUALTOUR,s.VIRTUALTOUR2)  is null then 0 else 1  end  
                                   else 0 end --as per SOT_GETVIRTUALTOUR function logic

,SHOWINGINSTRUCTION=s.SHOWINGINSTRUCTIONS
,AGENTREMARKS=s.AGENTREMARKS
,CALCPRICEPERABOVEGRADESQFT  
,LISTAGENTOFFICEPHONE=NULL
from dft_ECACMN s with (nolock)
WHERE IDCSTATUS IN ('Active','Pending','Active Under Contract','Coming Soon')
